name: aleivc CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2

      - name: login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: build and push image
        run: |
          bundle update webpacker
          rails webpacker:binstubs
          yarn upgrade @rails/webpacker --latest
          yarn upgrade webpack-dev-server --latest
          docker build -f Dockerfile -t aleivc .
          docker tag aleivc aleivc/aleivc:latest
          docker push aleivc/aleivc:latest
